### ISSUE TITLE
HW 2

### ISSUE THREAD

**Issue by almdudleer** [almdudleer/r-course#2]
HW2_implementation.* files in HW2 directory

**Comment by AntonZamyatin** [comment]
Hello,

1 In the `deal` function maybe it is better to use negative numbers for the subsetting?
2 When you knit your solution to pdf, please pay attention that lines in code chunks may overhang page borders.
3 Logic you use in `chance_to_win` is not a logic from the assignment. But ok let it be so because my assignment description is far from ideal.

Ok, thanks.
